### ISSUE TITLE
[BUG]: Repos[org][repo].Contents[path].GetAsync does not return file contents

### ISSUE THREAD

**Issue by qin-guan** [octokit/dotnet-sdk#105]
### What happened?

Calling the `Repo[org][repo].Contents[path].GetAsync()` function does not deserialize the response correctly.

In the HTTP response, there is a `content` key which should be deserialized, but the parser appears to look at `content-file` instead.

For now I am using a workaround by manually getting the request information and sending it to `HttpClient`, which provides the correct response.

### Versions

GitHub.Octokit.SDK v0.0.23
.NET v8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Thank you for reporting. Do you mind sharing a code snippet of the workaround you're using? 

I wonder if we have a broader pattern of schema errors with discriminator property names.

**Comment by qin-guan** [comment]
Hey, sure! Some rough code below

```csharp

public class GitHubFileContentHttpClient(HttpClient httpClient)
{
    /// <summary>
    /// Sends a request for <see cref="WithPathItemRequestBuilder.WithPathItemRequestBuilderGetQueryParameters"/>
    /// </summary>
    /// <param name="requestMessage">Message after using <see cref="Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter"/> ConvertToNativeRequestAsync</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>If the file was found, return <see cref="GetRepoContentResponse"/>. Else, return null</returns>
    /// <exception cref="Exception">Non success status code response, other than NotFound</exception>
    public async Task<(string, GetRepoContentResponse)?> GetFileContentAsync(
        HttpRequestMessage requestMessage,
        CancellationToken ct
    )
    {
        var rawRes = await httpClient.SendAsync(requestMessage, ct);
        if (rawRes.StatusCode == HttpStatusCode.NotFound)
        {
            return null;
        }

        if (rawRes.StatusCode != HttpStatusCode.OK)
        {
            throw new Exception(
            $"Expected success status code for {requestMessage.RequestUri} but received {rawRes.StatusCode}.");
        }

        var res = await rawRes.Content.ReadFromJsonAsync<GetRepoContentResponse>(cancellationToken: ct);
        if (res is null)
        {
            return null;
        }

        return (await httpClient.GetStringAsync(res.DownloadUrl, ct), res);
    }
}

```

To use

```csharp

var kiotaFileRequestInformation =
    gitHubClient.Repos[orgName][repo.Name]
        .Contents[filePath]
        .ToGetRequestInformation(
            options =>
            {
                options.QueryParameters.Ref = branch.Name;
                options.Headers["accept"] = ["application/vnd.github+json"];
            });

var reqInfo = await requestAdapter.RequestAdapter
    .ConvertToNativeRequestAsync<HttpRequestMessage>(
        kiotaFileRequestInformation);

var fileContentResponse = await gitHubFileContentClient.GetFileContentAsync(reqInfo);
if (!fileContentResponse.HasValue)
{
    return;
}
```

**Comment by qin-guan** [comment]
> I wonder if we have a broader pattern of schema errors with discriminator property names.

It could be the case, the OpenAPI spec file looks correct to me, so this could also be an upstream issue with Kiota

**Comment by nickfloyd** [comment]
Hey @qin-guan we finally tracked this down - it has to do with the fact that our OpenAPI definitions for content does not have a discriminator in it to help it understand what, of the 4 types, should it be.

I'm working to get a PR in to change this in the GitHub OpenAPI definitions and will let you know when that has shipped.

**Comment by nickfloyd** [comment]
@qin-guan Just a quick update.  I have created a PR for the GitHub OpenAPI descriptions that should fix this issue.  Once merged our auto generation should take over and update the the SDKs to fix the issue.  I'll let you know when that happens.

**Comment by qin-guan** [comment]
Hey @nickfloyd thanks for the updates!! So glad to see that a fix has been found, thank you! Happy to test it out once it's been released

**Comment by qin-guan** [comment]
Hey! Thanks for the updates yet again!! I look forward to seeing it out 🎉

**Comment by nickfloyd** [comment]
This has been fixed and released: https://github.com/octokit/dotnet-sdk/releases/tag/v0.0.30
