### ISSUE TITLE
The SDK return a List of String when it should return a List of Label [BUG]: 

### ISSUE THREAD

**Issue by Hossain2024** [octokit/dotnet-sdk#107]
### What happened?

I am encountering an issue while trying to get Label objects for an Issue in GitHub. 

https://github.dev/octokit/dotnet-sdk/blob/main/src/GitHub/Repos/Item/Item/Issues/IssuesRequestBuilder.cs

The GitHub.Models.Issue class defines the label property as a `List<string>`.  Based on the API response it should be a ``List<Label>```. 
```
   public long? Id { get; set; }
        /// <summary>Labels to associate with this issue; pass one or more label names to replace the set of labels on this issue; send an empty array to clear all labels from the issue; note that the labels are silently dropped for users without push access to the repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Labels { get; set; }
#nullable restore
#else
        public List<string> Labels { get; set; }
#endif
```

**The API URL:** 

https://api.github.com/repos/microsoft/kiota/issues/5037
```
"labels": [
        {
            "id": 2603543073,
            "node_id": "MDU6TGFiZWwyNjAzNTQzMDcz",
            "url": "https://api.github.com/repos/microsoft/kiota/labels/type:bug",
            "name": "type:bug",
            "color": "d73a4a",
            "default": false,
            "description": "A broken experience"
        },
        {
            "id": 3016728568,
            "node_id": "MDU6TGFiZWwzMDE2NzI4NTY4",
            "url": "https://api.github.com/repos/microsoft/kiota/labels/Python",
            "name": "Python",
            "color": "0BBE2D",
            "default": false,
            "description": ""
        }
   ]
```
In this API response the issues list is a  `List<Label>`

### Versions

0.0.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@Hossain2024 you're mixing up a request and a response there. In your first code snippet, you've quoted a comment that includes "pass one or more label names to replace the set of labels", implying a POST or a PUT request, and linked IssuesRequestBuilder.cs, which is what is sent to the API. 

In the second, you've shown a list of issues from the response, what is returned from the API. 

A list of strings is sent in the request to associate an issue with a given label (for which the string is the label name). A list of objects representing a label is returned in the response, for which not only the string label name is returned, but also the color, the description, the default, and various other fields.
