### ISSUE TITLE
[FEAT]: Better mocking support for GitHubClient

### ISSUE THREAD

**Issue by StevenJDH** [octokit/dotnet-sdk#129]
### Describe the need

I recently had a requirement to mock the GitHubClient that is injected into my service class in order to test the business logic of that class. However, when using Moq, I encountered the message about not being able to mock because of non-overridable members, in this case, `WithRefItemRequestBuilder.GetAsync`. Here is one example under .NET 8:

```csharp

var gitRef = new GitRef
{
    Ref = "refs/heads/test"
};

var tokenProvider = new BaseBearerTokenAuthenticationProvider(new TokenProvider("123456"));
var mockGitHub = new Mock<GitHubClient>(RequestAdapter.Create(tokenProvider))

mockGitHub.Setup(x => x.Repos[It.IsAny<string>()][It.IsAny<string>()].Git.MatchingRefs[It.IsAny<string>()]
                .GetAsync(It.IsAny<Action<RequestConfiguration<DefaultQueryParameters>>?>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync([gitRef]);
```

It's a bit verbose due to optional parameters having to be specified, but essentially, the `GetAsync` method, which comes from `GitHub.Repos.Item.Item.Git.MatchingRefs.Item.WithRefItemRequestBuilder` is the culprit. I've also tried instead mocking the adapter since this method calls `RequestAdapter.SendCollectionAsync<GitRef>()` under the hood, but either it wasn't working or I did it wrong.

My wish is that there be an IGitHubClient or other type of interface that could be used for testing, or make the methods virtual so that they were more test friendly.

### SDK Version

octokit/dotnet-sdk v0.0.28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Hmm...this is a great question. Perhaps it's something that should be filed in the [Kiota repo](https://github.com/microsoft/kiota), as our client is generated using the Kiota client. I wonder how they'd recommend mocking and testing. 

Of course, there's always the idea to introduce a layer of abstraction in your application and mock that, but I wonder what the Kiota team would suggest.

**Comment by StevenJDH** [comment]
> Hmm...this is a great question. Perhaps it's something that should be filed in the [Kiota repo](https://github.com/microsoft/kiota), as our client is generated using the Kiota client. I wonder how they'd recommend mocking and testing.
> 
> Of course, there's always the idea to introduce a layer of abstraction in your application and mock that, but I wonder what the Kiota team would suggest.

Makes sense now that you mention it. I've raised a new feature request for this with them now under microsoft/kiota#5560 to continue the discussion there. Thank you!
