### ISSUE TITLE
[BUG]: Tarball/Zipball - Return a Task not any content

### ISSUE THREAD

**Issue by MarkEnverus** [octokit/dotnet-sdk#71]
### What happened?

https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-tar
downloading a repo gets a Location header and downloads the binary content in Zip/Tar - currently the API only returns a Task so not data is returned
https://github.com/octokit/dotnet-sdk/blob/239513db62e94366d8305000f5400096e650e5f8/src/GitHub/Repos/Item/Item/Tarball/Item/WithRefItemRequestBuilder.cs#L48

### Versions

.net v8 
0.0.14 dotnet-sdk

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
This is interesting! GitHub returns a 302 that redirects to the actual content. That 302 (and the type of the actual content) isn't getting picked up at generation time. Kiota [does follow 302s](https://github.com/microsoft/kiota-http-go/blob/59b1f5f55ea11cb26ae8f1b6774bc1d41d7c43e4/redirect_handler.go#L147) in the redirect handler by default, which [we do implement](https://github.com/octokit/dotnet-sdk/blob/9499f482296c5054736631f723a82bb06bf62ac4/src/Client/ClientFactory.cs#L107C36-L107C54), so the redirect _should_ be getting followed. 

What's interesting is that in the specification, the redirect looks like this: 

```json
        "responses": {
          "302": {
            "description": "Response",
            "headers": {
              "Location": {
                "example": "https://codeload.github.com/me/myprivate/legacy.zip/master?login=me&token=thistokenexpires",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
```

**Comment by kfcampbell** [comment]
I've filed https://github.com/microsoft/kiota/issues/5208 with Kiota to double-check, but I believe this is a spec issue: we shouldn't be showing the redirect as a response in the spec, and instead we should be showing _where_ the redirect lands us.
