### ISSUE TITLE
int32 overflow deserializing generated models

### ISSUE THREAD

**Issue by martincostello** [octokit/dotnet-sdk#98]
@kfcampbell Sorry, it's still broken. Looks like the exact property I have an issue with escaped the changes:

https://github.com/octokit/dotnet-sdk/blob/e4bb0f0bf57a34ed2fcc8b9911c5eb536e90a650/src/GitHub/Models/EnvironmentObject.cs#L34

_Originally posted by @martincostello in https://github.com/octokit/dotnet-sdk/issues/95#issuecomment-2208249482_

**Comment by kfcampbell** [comment]
Good catch, thanks @martincostello! I'm working on pushing some changes through internally that should fix this.

**Comment by martincostello** [comment]
Resolved by #101.
